import { primaryKey } from '@mswjs/data';

export const policyManagementPolicy = {
  ObjectUUID: primaryKey(String),
  ObjectID: String,
  ObjectType: String,
  name: String,
  description: String,
  review_approval_required: Boolean,
  language: String,
  organization: String,
  review_period: String,
  days_earlier: Number,
  system_or_service: String,
  processing_activities: String,
  attach_file: String,
  personalize: {
    form_fields: {
      form: Array,
    },
    content: {
      header_logo: String,
      action: String,
    },
  },
  action: String,
  policy_type: String,
  template: {
    template_id: String,
    template_name: String,
  },
  website: String,
  status: String,
  signing_date: String,
  effective_date: String,
  preview_document: Array,
  workflow: Array,
  created_dt: String,
  created_by: String,
  updated_at: String,
  updated_by: String,
  policy_created_form: String,
  version: String,
};

export const policyManagementPolicyVersion = {
  ObjectUUID: primaryKey(String),
  ObjectID: String,
  ObjectType: String,
  name: String,
  description: String,
  review_approval_required: Boolean,
  language: String,
  organization: String,
  review_period: String,
  days_earlier: Number,
  system_or_service: String,
  processing_activities: String,
  attach_file: String,
  personalize: {
    form_fields: {
      form: Array,
    },
    content: {
      header_logo: String,
      action: String,
    },
  },
  action: String,
  policy_type: String,
  template: {
    template_id: String,
    template_name: String,
  },
  website: String,
  status: String,
  signing_date: String,
  effective_date: String,
  preview_document: Array,
  workflow: Array,
  created_dt: String,
  created_by: String,
  updated_at: String,
  updated_by: String,
  policy_created_form: String,
  version: String,
  versionId: String,
};
